EXTRA_DIST = README.md AUTHORS _config.yml

include_HEADERS = include/p3dfft.h include/p3dfft.mod

SUBDIRS = build sample

all-local:
	@echo $(SUCCESS)
clean-local:
	-[ -z "include/p3dfft.mod"] || rm -f include/p3dfft.mod
