
GIT_DATE=2021-5-11
GIT_VERSION=0
FC = mpif90
LD = $(FC)
FFTW_LIB = -L$(FFTWHOME)/lib -lfftw3 -lfftw3f
p3dfft_topdir = ../..
FCFLAGS =
#-I$(p3dfft_topdir)/include 
LDFLAGS = -lm -L$(p3dfft_topdir)/build -lp3dfft.3 $(FFTW_LIB) wrap.o p3dfft++.o -lstdc++

test3D_r2c.o: test3D_r2c.f90
	      $(LD) -c test3D_r2c.f90 $(FCFLAGS)

all: test3D_r2c.o
	$(LD) test3D_r2c.o $(LDFLAGS) -o test3D_r2c_f

	      